config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "/"  , to: "main#index"
  post "/login", to:  "main#valid"
  get "/dashboard", to: "main#dash"
  post "/book", to: "main#book"
  get "/bookHall", to: "main#booking"
  post "/bookHall", to: "main#checkBooking"
  post "/pending", to: "main#apprej"
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
    end

    def valid
        
        @check = Admin.find_by(admin_id: params[:admin_id], password: params[:password])
        if @check
            session[:admin_id] = params[:admin_id]
            redirect_to dashboard_path
        else
            flash[:error] = "Invalid credentials. Please try again."
            redirect_to '/'
        end

    end
    
    def dash
        @halls = Hall.all

        query5="SELECT * FROM hallbookings, admins, halls WHERE hallbookings.admin_id = admins.admin_id AND hallbookings.hall_id = halls.hall_id AND hallbookings.is_approved = 0"
        @hallbookings=Hallbooking.find_by_sql(query5)

        @keyholders = User.joins(
            "INNER JOIN key_assignments ON users.user_id = key_assignments.user_id " \
            "INNER JOIN classrooms ON key_assignments.room_id = classrooms.room_id"
            )
            .where(key_assignments: { is_returned: false })
            .select(
            'users.name AS user_name',
            'users.phone_number AS user_phone_number',
            'classrooms.room_no AS room_number',
            'classrooms.building AS building'
            )
            .distinct
    end

    def apprej

        if params[:commit_action] == "Approve"

            booking_to_update=Hallbooking.find_by(hall_id: params[:hallbooking]["hall_id"], 
                                            admin_id: params[:hallbooking]["admin_id"], 
                                            start_time: params[:hallbooking]["start_time"],
                                            end_time: params[:hallbooking]["end_time"],
                                            is_approved: 0)

            error_flag=0
            # @bookings_to_check=Hallbooking.find_by(hall_id: params[:hallbooking]["hall_id"], date_: params[:hallbooking]["date_"], is_approved: 1)
            query7 = "SELECT * FROM hallbookings where hall_id = ? and date_ = ? and is_approved = 1"
            @bookings_to_check = Hallbooking.find_by_sql([query7,params[:hallbooking]["hall_id"],params[:hallbooking]["date_"]])
            # @bookings_to_check = Array(@bookings_to_check) 
            # puts (@bookings_to_check)
            if @bookings_to_check
                @bookings_to_check.each do |booking|
                    puts "########PPPPRKLGJQERYJE%YJ%!!!!!!!!!!!!!!!!!!!"
                    # puts (booking.start_time <= booking_to_update.start_time)
                    puts (booking.start_time <= booking_to_update.start_time )
                    puts (booking.end_time >= booking_to_update.end_time)
                    puts (booking.end_time)
                    puts (booking_to_update.end_time)
                    if (
                        (booking.start_time <= booking_to_update.start_time && booking.end_time >= booking_to_update.start_time) || 
                        (booking.start_time <= booking_to_update.end_time && booking.end_time >= booking_to_update.end_time) || 
                        (booking.start_time >= booking_to_update.start_time && booking.end_time <= booking_to_update.end_time) ||
                        (booking.start_time <= booking_to_update.start_time && booking.end_time >= booking_to_update.end_time)
                        ) 
                            error_flag=1
                    end
                end
            end

            if(error_flag == 0)
                if booking_to_update.update(is_approved: 1)
                    flash[:success] = "Approval Successful"
                    redirect_to dashboard_path
                else
                    flash[:error] = "Approval Failed"
                    redirect_to dashboard_path
                end
            else
                if booking_to_update.destroy
                    flash[:error] = "Deleted Due to Clash"
                    redirect_to dashboard_path
                else
                    flash[:error] = 'Failed to delete the record regardless or clash: db error.'
                    redirect_to dashboard_path
                end
            end
            
        elsif params[:commit_action] == "Reject"
            booking_to_delete=Hallbooking.find_by(hall_id: params[:hallbooking]["hall_id"], 
                                        admin_id: params[:hallbooking]["admin_id"], 
                                        start_time: params[:hallbooking]["start_time"],
                                        end_time: params[:hallbooking]["end_time"],
                                        is_approved: 0)
            if booking_to_delete.destroy
                flash[:success] = 'Record was successfully deleted.'
                redirect_to dashboard_path
            else
                flash[:error] = 'Failed to delete the record.'
                redirect_to dashboard_path
            end
        end

    end
    
    def book
        @hallName = Hall.find_by(hall_id: params[:hall_id])
        if @hallName
            session[:hall_name] = @hallName.hall_name
            session[:hall_id] = @hallName.hall_id
            session[:location] = @hallName.location
            redirect_to bookHall_path
        end
    end

    def booking
        @name = session[:hall_name]
        @id = session[:hall_id]
        @loc = session[:location]
        @obj = session[:hall]
    end 

    def checkBooking
        @bookingDetails = Hallbooking.find_by(date_: params[:date_], start_time: params[:start_time], end_time: params[:end_time], hall_id: session[:hall_id],is_approved:1)
        if @bookingDetails
            flash[:error] = "Hall Occupied"
            redirect_to bookHall_path
            return
        else
            @today = Date.today
            if Date.parse(params[:date_]) < @today
                flash[:error] = "Invalid date chosen."
                redirect_to bookHall_path
                return
            end
            if Date.parse(params[:date_]) == @today && params[:start_time] > params[:end_time]
                flash[:error] = "Invalid timings."
                redirect_to bookHall_path
                return
            end
            if params[:end_time] < params[:start_time]
                flash[:error] = "Invalid timings."
                redirect_to bookHall_path
                return
            end
            @query1 = Hallbooking.find_by(date_: params[:date_], start_time: params[:start_time], end_time: params[:end_time], hall_id: session[:hall_id], is_approved: 1)
            if @query1
                flash[:error] = "Hall is busy. Please choose another slot."
                redirect_to bookHall_path
                return
            else
                query2 = "select * from hallbookings where date_ = ? and strftime('%H:%M', start_time) < ? and strftime('%H:%M', end_time) > ? and hall_id = ? and is_approved = 1";
                results2 = Hallbooking.find_by_sql([query2,params[:date_],params[:start_time],params[:start_time],session[:hall_id]])
                if results2.present?
                    flash[:error] = "Hall is busy. Please choose another slot."
                    redirect_to bookHall_path
                    return
                else
                    query3 = "select * from hallbookings where date_ = ? and strftime('%H:%M', start_time) < ? and strftime('%H:%M', end_time) > ? and hall_id = ? and is_approved = 1";
                    results3 = Hallbooking.find_by_sql([query3,params[:date_],params[:end_time],params[:end_time],session[:hall_id]])
                    if results3.present?
                        flash[:error] = "Hall is busy. Please choose another slot."
                        redirect_to bookHall_path
                        return
                    else
                        query4 = "select * from hallbookings where date_ = ? and strftime('%H:%M', start_time) > ? and strftime('%H:%M', end_time) < ? and hall_id = ? and is_approved = 1";
                        results4 = Hallbooking.find_by_sql([query4,params[:date_],params[:start_time], params[:end_time], session[:hall_id]])
                        if results4.present?
                            flash[:error] = "Hall is busy. Please choose another slot."
                            redirect_to bookHall_path
                            return
                        else
                            new_booking = Hallbooking.new(
                                                            date_: Date.parse(params[:date_]),
                                                            start_time: params[:start_time],
                                                            end_time: params[:end_time],
                                                            hall_id: session[:hall_id],
                                                            admin_id: session[:admin_id],
                                                            reason: params[:reason],
                                                            is_approved: 0
                                                            )
                            
                            if new_booking.save
                                flash[:success] = "Hall booking request sent. Please await approval from competent authority."
                                redirect_to dashboard_path
                                return
                            else
                                flash[:error] = "Error creating booking: #{new_booking.errors.full_messages.to_sentence}"
                                redirect_to bookHall_path
                                return
                            end
                        end
                    end
                end
            end
        end
        # redirect_to dashboard_path
    end
end

app/views/main/booking.html.erb
<div class="main">
            <main class="col-md-1 ms-sm-auto col-lg-1 justify-content-center main" style="margin-left:30%;">
                <!-- Change Password Form Inside Card -->
                <div class="card mt-1 justify-content-center" style="width:fit-content;margin-left:30%;">
                    <% if flash[:error] %>
                        <div class="alert alert-danger text-center"role="alert">
                        <%= flash[:error] %>
                        </div>
                    <% end %>
                    <div class="card-body align-items-center justify-content-center text-center" style="width:min-content; margin-left:auto;">
                        <h2 class="card-title">Book Hall</h2>
                        <!-- Add a form here for changing the password -->
                        <%= form_with model: @hallbooking, url: bookHall_path, html: { style: "width: max-content;" } do |form| %>
                            <% if @name %>
                            <h5>Booking for Hall: <%= @name %></h5>
                            <% end %>
                            <% if @loc %>
                            <h5>Location: <%= @loc %></h5>
                            
                            <% end %>
                            
                            <br>
                            <div class="form-group text-left">
                                
                                <%= form.label :date, "Date<span class='required' style='color:red;'>*</span>".html_safe %>
                                <%= form.date_field :date_, class: "form-control", required: true %>
                                </div>
                            <br>
                            <div class="form-group text-left">
                                <%= form.label :StartTime, "Start Time<span class='required' style='color:red;'>*</span>".html_safe %>
                                <%= form.time_field :start_time, class: "form-control", required: true %>
                            </div>
                            <br>
                            <div class="form-group text-left">
                            <%= form.label :EndTime, "End Time<span class='required' style='color:red;'>*</span>".html_safe %>
                            <%= form.time_field :end_time, class: "form-control", required: true%>
                            </div>
                            <br>
                            <div class="form-group text-left">
                                <%= form.label :reason, "Reason<span class='required' style='color:red;'>*</span>".html_safe %>
                                <br>
                                <%= text_area_tag 'reason', nil, cols: 56, rows: 3, class: 'form-control', required: true %>
                            </div>
                            <br>
                            <%= form.submit "Request", class: "btn btn-primary" %>
                        <%end%>
                    </div>
                </div>
            </main>
        </div>

app/views/main/dash.html.erb
<!-- Main Component -->
<div class="main">
    
    <main class="content px-3 py-2">
        <div class="container-fluid">
            <div class="container col-md-9 ms-sm-auto col-lg-10 px-md-4">
                <div class="row mt-5 justify-content-center">
                    <div >
                        <div class="card">
                        <% if flash[:error] %>
                            <div class="alert alert-danger text-center"role="alert">
                            <%= flash[:error] %>
                            </div>
                        <% end %>
                        <% if flash[:success] %>
                            <div class="alert alert-success text-center"role="alert">
                            <%= flash[:success] %>
                            </div>
                        <% end %>
                            <div class="card-header">
                                <ul class="nav nav-tabs card-header-tabs">
                                    <li class="nav-item">
                                        <a class="nav-link active" href="#view-halls" data-toggle="tab">View Halls</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="#pending-requests" data-toggle="tab">Requests Pending </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="#view-keyholders" data-toggle="tab">View Keyholders</a>
                                    </li>
                                    
                                </ul>
                            </div>
                            <div class="card-body">
                                <div class="tab-content">
                                    <div class="tab-pane fade show active" id="view-halls">
                                        <ul class="list-group">
                                        <% @halls.each do |hall| %>
                                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                            <%= hall.hall_name %>
                                            <%= form_with model: @hall, url: book_path do |form| %>
                                                <%= form.hidden_field :hall_id, value: hall.hall_id %>
                                                <%= form.hidden_field :hall_name, value: hall.hall_name %>
                                                <%= form.submit "Book Hall", class: "btn btn-primary" %>
                                            <% end %>
                                            </li>
                                        <% end %>
                                        </ul>
                                    </div>

                                    <div class="tab-pane fade" id="pending-requests">
                                        <ul class="list-group">
                                        <% @hallbookings.each do |hallbookings| %>
                                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                            Booked By: <%= hallbookings.name %><br>
                                            Hall Name: <%= hallbookings.hall_name %><br>
                                            Date: <%= hallbookings.date_ %><br>
                                            From: <%= hallbookings.start_time.strftime('%H:%M:%S') %><br>
                                            To: <%= hallbookings.end_time.strftime('%H:%M:%S') %><br>
                                            Reason: <%= hallbookings.reason %><br>
                                            <%= form_with(model: @hallbookings, url:pending_path, method: 'post') do |form| %>
                                                <%= form.hidden_field :hall_id, value: hallbookings.hall_id %>
                                                <%= form.hidden_field :admin_id, value: hallbookings.admin_id %>
                                                <%= form.hidden_field :start_time, value: hallbookings.start_time %>
                                                <%= form.hidden_field :end_time, value: hallbookings.end_time %>
                                                <%= form.hidden_field :date_, value: hallbookings.date_ %>
                                                <%= form.submit "Approve", name: "commit_action", value: "Approve", class: "btn btn-primary" %>
                                                <%= form.submit "Reject", name: "commit_action", value: "Reject", class: "btn btn-primary" %>
                                            <% end %>
                                            </li>
                                        <% end %>
                                        </ul>
                                    </div>
                                    <div class="tab-pane fade show" id="view-keyholders">
                                    <ul class="list-group">
                                      <% @keyholders.each do |keyholder| %>
                                        <li class="list-group-item">
                                          <strong>Name:</strong> <%= keyholder.user_name %><br>
                                          <strong>Location:</strong> <%= keyholder.building %> <%= keyholder.room_number %><br>
                                          <strong>Phone Number:</strong> <%= keyholder.user_phone_number %>
                                        </li>
                                      <% end %>
                                    </ul>
                                  </div>
                                  
                                    
                                </div> 
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
crossorigin="anonymous"></script>

<!-- Include Bootstrap JS and jQuery script links here -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<script>

app/views/main/index.html.erb
<div class="container">
        <div class="row mt-5 justify-content-center">
            <div class="col-md-6">
                    <div class="card">
                    <% if flash[:error] %>
                    <div class="alert alert-danger text-center"role="alert">
                    <%= flash[:error] %>
                    </div>
                    <% end %>
                    <div class="card-header">
                        <ul class="nav nav-tabs card-header-tabs">
                            <li class="nav-item">
                                <a class="nav-link " href="#student-tab" data-toggle="tab">Student</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#teacher-tab" data-toggle="tab">Teacher</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" href="#admin-tab" data-toggle="tab">Admin</a>
                            </li>
                        </ul>
                    </div>
                    <div class="card-body">
                        <div class="tab-content">
                            <div class="tab-pane fade" id="student-tab">
                                
                            </div>
                            <div class="tab-pane fade" id="teacher-tab">
                                <!-- Teacher login form similar to student form -->
                            </div>
                            <div class="tab-pane fade  show active" id="admin-tab">
                                <%= form_with model: @admin, url: login_path do |form| %>
                                    <div class="form-group">
                                        <%= form.label :username %>

                                        <%= form.text_field :admin_id, class: "form-control", placeholder: "Enter username" %>
                                    </div>
                                    <div class="form-group">
                                        <%= form.label :password %>

                                        <%= form.password_field :password ,class:"form-control", placeholder: "Enter password" %>
                                    </div>

                                    <%= form.submit "Login", class: "btn btn-primary" %>

                                <%end%>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Include Bootstrap JS and jQuery script links here -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>